graph TD
  T0(BPE DETAIL Dataset)

  T1(CENSUS Dataset)

  S1(Validation of municipality code in input file)
  
  S2(BPE DETAIL cleaning)

  S3(Municipality aggregation)

  S4(Nuts 3 aggregation)

  S5(Validation of facility types in Nuts 3)

  S6(CENSUS cleaning)

  S7(Extract general practitioners from BPE by Nuts 3)

  S8(Merge sources and compute an indicator)

  T0-->|1|S1

  T0-->|2|S2

  S2-->|3|S3

  S3-->|4|S4

  S4-->|5|S5

  S4-->|7|S7

  T1-->|6|S6

  S6-->|8|S8
  S7-->|8|S8
